// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

/* eslint-disable @typescript-eslint/no-explicit-any */
const SUPABASE_URL =
  typeof window !== "undefined"
    ? import.meta.env.VITE_SUPABASE_URL || ""
    : process.env.SUPABASE_URL || "";
const SUPABASE_PUBLISHABLE_KEY =
  typeof window !== "undefined"
    ? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || ""
    : process.env.SUPABASE_PUBLISHABLE_KEY || "";

const hasCredentials = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
const isMock =
  !hasCredentials ||
  (typeof window !== "undefined" &&
    (window.location.search.includes("mock=true") ||
      (window as any).__selenium_mock__ === true ||
      localStorage.getItem("selenium_mock") === "true"));

const mockListeners = new Set<(event: string, session: any) => void>();
let mockSession: any = null;

const mockSupabase = {
  auth: {
    onAuthStateChange(callback: any) {
      mockListeners.add(callback);
      // Execute microtask to let the caller register before callback fires
      setTimeout(() => {
        callback(mockSession ? "SIGNED_IN" : "SIGNED_OUT", mockSession);
      }, 0);
      return {
        data: {
          subscription: {
            unsubscribe() {
              mockListeners.delete(callback);
            },
          },
        },
      };
    },
    async getSession() {
      return { data: { session: mockSession } };
    },
    async getUser() {
      return {
        data: { user: mockSession ? { id: "test-user-id", email: "test@example.com" } : null },
      };
    },
    async signInWithPassword({ email, password }: any) {
      mockSession = {
        access_token: "mock-token",
        user: { id: "test-user-id", email: "test@example.com" },
      };
      for (const listener of mockListeners) {
        listener("SIGNED_IN", mockSession);
      }
      return { data: { session: mockSession, user: mockSession.user }, error: null };
    },
    async signOut() {
      mockSession = null;
      for (const listener of mockListeners) {
        listener("SIGNED_OUT", null);
      }
      return { error: null };
    },
  },
  from(table: string) {
    const resultPromise = Promise.resolve({ data: [], error: null });
    const chain = {
      select(columns: string) {
        return chain;
      },
      order(column: string, options: any) {
        return chain;
      },
      limit(n: number) {
        return chain;
      },
      delete() {
        return chain;
      },
      eq(column: string, value: any) {
        return chain;
      },
      maybeSingle() {
        return Promise.resolve({
          data: {
            display_name: "Test User",
            night_mode_safety: true,
            avoid_isolated: false,
            prefer_crowded: true,
          },
          error: null,
        });
      },
      insert(data: any) {
        return Promise.resolve({ data, error: null });
      },
      then(onfulfilled: any, onrejected: any) {
        return resultPromise.then(onfulfilled, onrejected);
      },
    };
    return chain;
  },
  channel(name: string) {
    const ch = {
      on(event: string, filter: any, callback: any) {
        return ch;
      },
      subscribe() {
        return {};
      },
    };
    return ch;
  },
  removeChannel(channel: any) {},
};
/* eslint-enable @typescript-eslint/no-explicit-any */

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (isMock) {
      return Reflect.get(mockSupabase, prop, receiver);
    }
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
